**By:** *Ahmed Sharaf*

In this notebook you will practice how to:
1. Calculate the determinant of a 2x2 matrix with and without using numpy.linalg
2. Calculate the determinant of a 3x3 matrix with and without using numpy.linalg
3. Calculate the inverse of a 2x2 matrix using numpy.linalg
4. Calculate the inverse of a 3x3 matrix using numpy.linalg
5. Finding the rank of a matrix using numpy

### Notice

**Please Note:**  
When writing code, make sure to place it in the designated area marked with `# code here`.  
If there is a `pass` keyword in the code, please remove it and replace it with the required code.

# Calculating the determinant using numpy.linalg

In [151]:
import numpy as np

In [152]:
a2 = np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [153]:
a3 = np.array([[1,1,2],[2,3,1],[3,4,-5]])
print(a3)

[[ 1  1  2]
 [ 2  3  1]
 [ 3  4 -5]]


In [154]:
## Determinate of a2, a3
det_a2=(a2[0][0]*a2[1][1])-(a2[0][1]*a2[1][0])
print(det_a2)

det_a3 = (a3[0][0] * ((a3[1][1] * a3[2][2]) - (a3[1][2] * a3[2][1]))) - \
         (a3[0][1] * ((a3[1][0] * a3[2][2]) - (a3[1][2] * a3[2][0]))) + \
         (a3[0][2] * ((a3[1][0] * a3[2][1]) - (a3[1][1] * a3[2][0])))

print(det_a3)

-2
-8


# Calculating the determinant of a 2x2 matrixwithout using numpy

In [155]:
def Det2(Mat):
    if len(Mat) == 2 and len(Mat[0]) == 2 and len(Mat[1]) == 2:
        return (Mat[0][0] * Mat[1][1]) - (Mat[0][1] * Mat[1][0])
    else:
        return "Invalid matrix size"

print(Det2(a2))

-2


# Calculating the determinant of a 3x3 matrixwithout using numpy

One idea
1. write a function to calculate the minor matrices. (hint, use slices)
2. write a function to calculate the cofactors (this should call the first function, and the determinant function)
3. the determinant function calls the function in step two and adds the results together.

Another idea 
use recursion ==> code credit https://stackoverflow.com/questions/3819500/code-to-solve-determinant-using-python-without-using-scipy-linalg-det

In [156]:
# delete function removes a sub-array from the input array
# first argument is the original array
# second argument is the index to the sub-array to be removed
# third argument is the axis among which the deletion happens (0: x axis "row" and 1: y axis "column")
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
#axis=0>>row
arr2 = np.delete(arr, 1, 0)
print(arr2)
#axis=1>col
arr3 = np.delete(arr, 3, 1)
print(arr3)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [157]:
def minor(arr,i,j):
      return np.delete(np.delete(arr, i, axis=0), j, axis=1)

def det(arr):
    if len(arr) == 2:
        return arr[0][0] * arr[1][1] - arr[0][1] * arr[1][0]

    determinant = 0
    for j in range(len(arr[0])):
        cofactor = (-1) ** j * arr[0][j] * det(minor(arr, 0, j))

        determinant += cofactor

    return determinant

print(a3)
print(det(a3))


[[ 1  1  2]
 [ 2  3  1]
 [ 3  4 -5]]
-8


# Calculating the inverse using numpy.linalg

In [158]:
# The inverse of 2 x 2 matrix

a2 = np.array([[1,2],[3,4]])

print(a2)
inv_a2 = np.linalg.inv(a2)
print(inv_a2)

"""
def inverse_2x2(matrix):
    det = (matrix[0, 0] * matrix[1, 1]) - (matrix[0, 1] * matrix[1, 0])
    if det == 0:
        return "no solution"
    inv_matrix = (1 / det) * np.array([
        [matrix[1, 1], -matrix[0, 1]],
        [-matrix[1, 0], matrix[0, 0]]
    ])
    
    return inv_matrix

inv_a2 = inverse_2x2(a2)
print(inv_a2) 
"""


[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


'\ndef inverse_2x2(matrix):\n    det = (matrix[0, 0] * matrix[1, 1]) - (matrix[0, 1] * matrix[1, 0])\n    if det == 0:\n        return "no solution"\n    inv_matrix = (1 / det) * np.array([\n        [matrix[1, 1], -matrix[0, 1]],\n        [-matrix[1, 0], matrix[0, 0]]\n    ])\n    \n    return inv_matrix\n\ninv_a2 = inverse_2x2(a2)\nprint(inv_a2) \n'

In [159]:
# The inverse of a singular matrix

a3 = np.array([[1,2],[2,4]])

print(a3)

det_a3 = np.linalg.det(a3)

if det_a3 == 0:
    print("not allow")
else:
    inv_a3 = np.linalg.inv(a3)
    print(inv_a3)
        


[[1 2]
 [2 4]]
not allow


In [160]:
# The inverse of 3 x 3 matrix

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
inv_A = np.linalg.inv(A)
print(inv_A)


[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [161]:
# Inverses of several matrices can
# be computed at once

A = np.array([[[1., 2.], 
               [3., 4.]],
              [[1, 3], 
               [3, 5]]])
  
# Calculating the inverse of the matrix
inverses = np.linalg.inv(A)

print(inverses)

[[[-2.    1.  ]
  [ 1.5  -0.5 ]]

 [[-1.25  0.75]
  [ 0.75 -0.25]]]


# Calculating the inverse of a 2x2 matrixwithout using numpy

1. Code a function to calculate the determinant of 2x2 matrix
2. Code a function that interchange the diagonal elements of a 2x2 matrix and inverse the sign of the off diagonal elements
3. Code a function to compute the inverse of 2x2 matrix based on the two previous functions if it exists

In [162]:
#step -1- we already coded the det function that works for 2x2 and nxn size matrix
def det(A):
    return A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]
#step -2-
def interchangeMatrix(A):
   return [[A[1, 1], -A[0, 1]], [-A[1, 0], A[0, 0]]]

#step -3-
def inverse2x2(A):
    determinant = det(A)
    if determinant == 0:
        return "No solution"
    result = interchangeMatrix(A)
    inverse_matrix = [[result[0][0] / determinant, result[0][1] / determinant],
                      [result[1][0] / determinant, result[1][1] / determinant]]
    
    return inverse_matrix

      

a2 = np.array([[1,2],[3,4]])
print(inverse2x2(a2))

[[np.float64(-2.0), np.float64(1.0)], [np.float64(1.5), np.float64(-0.5)]]


# Calculating the inverse of a 3x3 matrixwithout using numpy

# Use the adjoint matrix method

Coding a Python code to inverse a 3x3 matrix (no numpy.linalg.inv allowed):
1. Coding a function that checks if a 3x3 matrix is invertible
2. Coding a function that generates the transpose of a 3x3 matrix
3. Coding a function that generates the matrix of minors of a 3x3 matrix
4. Coding a function that generates the matrix of cofactors of a 3x3 matrix
5. Coding a function that generates the inverse of a 3x3 matrix if it exists


In [163]:
#step -1- a matrix is invertible only if its determinant != 0
def invertible(A):
    det = (A[0][0] * (A[1][1] * A[2][2] - A[1][2] * A[2][1])) - \
          (A[0][1] * (A[1][0] * A[2][2] - A[1][2] * A[2][0])) + \
          (A[0][2] * (A[1][0] * A[2][1] - A[1][1] * A[2][0]))
    return det != 0

#step -2- rows and columns could be interchanged without the need of built-in methods
def transposeM(A):
    return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

#step -3- we coded that previously minor(arr,i,j)

#step -4- Calculating the matrix of cofactors (minors determinants multiplied by signs)
def cofactors(A):
    cofactors_matrix = []
    for i in range(3):
        row = []
        for j in range(3):
            cofactor_value = ((-1) ** (i + j)) * np.linalg.det(minor(A, i, j))
            row.append(cofactor_value)
        cofactors_matrix.append(row)
    return cofactors_matrix



#step -5- Inverse is the transpose of the cofactor matrix divided by the determinant of the original/input matrix
def inverse3x3(A):
    if not invertible(A):
        return "Matrix is not invertible"
    det_A = (A[0][0] * (A[1][1] * A[2][2] - A[1][2] * A[2][1])) - \
            (A[0][1] * (A[1][0] * A[2][2] - A[1][2] * A[2][0])) + \
            (A[0][2] * (A[1][0] * A[2][1] - A[1][1] * A[2][0]))
    cofactor_matrix = cofactors(A)
    adjugate_matrix = transposeM(cofactor_matrix)        
    inverse_matrix = [[adjugate_matrix[i][j] / det_A for j in range(3)] for i in range(3)]
    
    return inverse_matrix

B = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

print(inverse3x3(B))

#[ 0.17647059 -0.00326797 -0.02287582]
# [ 0.05882353 -0.13071895  0.08496732]
# [-0.11764706  0.1503268   0.05228758]]
#check
print(np.linalg.inv(B))

[[np.float64(0.17647058823529413), np.float64(-0.0032679738562091504), np.float64(-0.022875816993464054)], [np.float64(0.05882352941176469), np.float64(-0.13071895424836602), np.float64(0.08496732026143787)], [np.float64(-0.11764705882352941), np.float64(0.1503267973856209), np.float64(0.0522875816993464)]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


# Finding the rank of a matrix using numpy

In [164]:
a3 = np.array([[1,2],[2,4]])

rank_a3 = np.linalg.matrix_rank(a3)
print(rank_a3)

1
